server:
  port: 8889
sa-token:
  # -------------- SSO-模式一相关配置  (非模式一不需要配置)
  # cookie:
  # 配置Cookie作用域
  # domain: stp.com

  # SSO-相关配置
  sso:
    # SSO-Server端-单点登录授权地址
    auth-url: http://sso.stp.com:8889/sso/auth
    # SSO-Server端-单点注销地址
    slo-url: http://sso.stp.com:8889/sso/logout

  # 配置Sa-Token单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    # Redis数据库索引
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s

  #cookie:
    # 配置Cookie作用域
    # domain: stp.com

spring:
  # Redis配置 （SSO模式一和模式二使用Redis来同步会话）
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: